language: java
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
before_install: git clone -b travis `git config --get remote.origin.url` target/travis
before_script: mvn dependency:resolve -DoverWriteSnapshots=true
after_success: mvn clean deploy --settings target/travis/settings.xml -DskipTests=true
branches:
  only:
  - master
  - release
notifications:
  email:
    recipients:
    - vatbub123+travisbuildnotification@googlemail.com
    on_success: never
    on_failure: always
env:
  global:
  - secure: P30J5uQxZfmCX69FiFvz1Oz1LFC0po/XKuDQj7mirsTKk2WdITMKmNKr+gud+OEw3cC526Y6AT/6GEyO93r+P9lptzyUawPGeq4ZKKZobKJl+900sdos5/E0ls6c0TAtTjSlvfWvaKE3R3Y65cC4Wd/iNwoFVVZmM30OG01hLktUdpubYbhgUIK0yiB7zougRoqs5jcPBNBiVHsqN4dz+7KGwt+d6G9yGkk3WwTRoL+Fjj66f62jHFCdClwKheSsyEhq0cez3xySPASECqqEFvcACO5HQw6KhNiB1BkC2y1UiLsDwyLiu7BOQlnvlUaIDlqAXQGGEZTOHCvF25mX1WUG7KGuSrUjLhhKtsc3Int24jn4Dy9MPRpHERVR2PCBVpZHhJe1idmlx6ACTQTt+54yTUOD/I+UjlgpBXAac+VTkU6r3vvVs6E+zvfuLgeuuI9zZTjbjHL1TYGLCBKTj+3VthoowBoHfPKX+R3IEQpTtrL2Y94xTOFKijruE7cxXaYiTwq0g7kJvY76b2qBXO9WlAnHLqSr6ZxYbdsNMkN3jBvmmp97aAPEcUy+XDKdaijCmICmxpeN7WBmsYN5LM08SN6rIg/R8OvYjmSK8siKqu/XQeE8vsIq2mlde2ODZZRJktBEqpGuLB5q3AasW+9olIe7UT1AjPkJA27i5e0=
  - secure: vInj1Wwb1zvwJGPdTBx2kBtjsRwulvyzDr3tAUTZENQEZMJmrzGGL21dSxruXYxwaoDBOnE9pAljaEVBQE2BdejEg5sFCQcTfaRlWnWxnU/nOEKzddHnzwZYXe7zo0LVnf89KF/4atipMOKbiB4knNhI25vj50GfOSe797c2pOWhVZjoLT+2TquJY7VMpR7YRMA1elIRnrF0MQXy1ysnWuIsvxA1zLfrg5yhrc1UqKjlyEATTLNYHHvb5IF49MR0ydggOWAXzAxbEnJBqZbojb0529AIz39lua4TfYS5q2WnQYNJN+4iGI8YbPOf8eSH/Z/SiG8x5C/0r66PyOvZnFHqcSceeWPcoQVYeLsPOD27mkXDdtrwMT0/t3YMId7p+fLtQvqyDXHBEu8E0kJmdH+mT6NlsLXRvU8IoPqVWt60FFcpv57sn9tKk+E6alEfrbBEfmuEoa1YhIB1+s3YzkVyv9bWfrW/YjRAlzjQrbY+qH0HxNiwashEAdCttdiaSsbFVUptKXzqP10xryFejvIecopTTelT7WaXg396jFCCFVmh/h8gVkVLKIpEGcf9aS/JD+QVFaQEXnz7JNWrKr945S/8ye8XY2zh3Pqd5aKlILjRgjpLilqu9pR1upbFYq6h/L+pwDml2lZU3g4A0bSBdz6QjcK+Sv6nHTQ3cZ4=
