language: java
jdk:
- oraclejdk8
before_install: git clone -b travis `git config --get remote.origin.url` target/travis
after_success: mvn deploy
branches:
  only:
  - master
  - release
notifications:
  email:
    recipients:
    - vatbub123+travisbuildnotification@googlemail.com
    on_success: never
    on_failure: always
env:
  global:
  - secure: eOikzHBMq8rUcR8vaa/jfLGh6/ELVoDwumsB5mUWKfPx1Jqh00y8gGERGfcltOUhqOGQw0dcFnodKtLn0r1iBRDCoxio9194n3rQwTRMU/raIhE0/jvkQk8qDNeGh/gY+SlLwSq5Ht9je4QFLbi9rDTuwPeTXPGmkd4P5NFLFaNoPUMwjugYy027Of1UBQiWhP+YXvjuAxbqg4e/H1oaO89mr7T7oaqW0xcjgiNfuCaaDYZOiixGz+8GaNCA1/A4E+CDcwVozd3XTjSZdbYFjEMbnnQaswiyDp3uTGOI2/O2Gt3uMbGobmokz/FJrLUw/NcVsfuJpbo/sln8zOT3nPCuGZY+WBOH3tqo59t/4wIoFVzNnTHr/CUjHWcSSqUaV1fkAt7Hiz41Rve+kt5+ihabRG5qgPZGDT7+il8ArzcP2H4ZJyhXGyURPfOrxvOmJmVYedFsL2eS4tbz1eCdDzMBQn5DUMAEKMk358nINhPq1LmE1R41QFyDCQ6kb2m/K25XY2B5tzld6jndQlXKjg2jm1388oAXI3leIaw1G30PhunJeUpMWu9Dx0DQjZANGBSD5PbHwaSClU7q4W84wP9Xh+bjttBkxi8SH2eJs31x+PROOa7AVplZY9YHl9uukWAx1NfDOqaRKnGe9jKZjt1zZ5ZZ0Wu6Vz+ytqzKUF0=
  - secure: KYEVy1zxUm/Kxy9w4dm9yfdMwGWJDWhymCXP8iExcJ5hsLvD6ptAQD3U0PpjAo4YxNp1668r8NQoHI5kA7iFUdG83pVLbDIlQg4yfEFqdZ20tzQ0mciA72aP0hg3HN2Ss4NU0tgrd6B7KSevt8qYss/VrxFEAE8T1vP+aEK7HrM127mI28+IddgGrpvacgxAFTehE+9EYIBHLDCfCYJuq5CI8PdgTuIeTgYnM7tQlnEZDUHNlwwmASdNlYmhDLNv4PB+bFo3NR06+PMQ81vVPeb/VLNeDQZpTvy0Wj8Bssi0sCHlxtTfpJxeRmaKnXq8XpyLqLZIecPn1gMcvJljZfLG64qq/XtXw9EC0M/3HjmDelVBCUisBnH1XLRqu9facpfVO3uFPNCgNezPmj2HNfHmZXt2IeTqKHVrnP573s+H9nxWWoOvf7HUzDW3ym2YmBdjn49sF3bGJRm5mPp8Z0swDkUEMCYtlsb6hdpudMlacF7kPlral62HuRfXh6gFU3eMNgJU1I2s/OnddXJuVn6738W3HBxMQ0/Dtz5kDiYRU8iYvyweqf1WrQbm9JtQkPrVrLHK4EWuHi805GC68DsLjUiZN65CI3GwsCjKuS6QG1j+pcQpu1RuF32kdMCq8Xt6S0QhQKzghjdSxoqV+nbVN7JLEO3acD7NBkbVj3c=
